context:
  version: 0.19.0

package:
  name: aerc
  version: ${{ version }}

source:
  - url: https://git.sr.ht/~rjarry/aerc/archive/${{ version }}.tar.gz
    sha256: caf830959cf689db257ffb64893fd78f1a362a22fe774dd561340fc552d599eb

build:
  number: 0
  skip:
    - win
  script:
    - make VERSION=${{ version }} BUILD_OPTS="-buildmode=pie -trimpath" GO_EXTRA_LDFLAGS="-s -w"
    - make install
    - go-licenses save . --save_path=license-files
    # Clear out cache to avoid file not removable warnings
    - if: unix
      then: chmod -R u+w $(go env GOPATH) && rm -rf $(go env GOPATH)

requirements:
  build:
    - ${{ compiler("go-cgo") }} >=1.21
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - go-licenses
    - make
    - scdoc

tests:
  - package_contents:
      files:
        - share/aerc/aerc.conf
        - share/aerc/stylesets/default
        - share/man/man1/aerc.1
        - libexec/aerc/filters/calendar
      bin:
        - aerc
  - script:
      - aerc -h

about:
  homepage: https://aerc-mail.org/
  summary: aerc is an email client for your terminal
  description: |
    aerc is an email client for your terminal.

    This is a fork of the original aerc by Drew DeVault.

    A short demonstration can be found on https://aerc-mail.org/

    Join the IRC channel: #aerc on irc.libera.chat for end-user support, and development.
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  documentation: https://man.sr.ht/~rjarry/aerc/
  repository: https://git.sr.ht/~rjarry/aerc

extra:
  recipe-maintainers:
    - blmaier
